#ifndef SUPPORT_XBAR_H_
#define SUPPORT_XBAR_H_

#define XBAR_FLAG_BASE              (0x00007920UL)
#define XBAR_INPUT_BASE             (0x00007900UL)
#define XBAR_CLB_INPUT_BASE         (0x00007960UL)
#define XBAR_TRIP_BASE              (0x00007A00UL)
#define XBAR_CLB_BASE               (0x00007A40UL)
#define XBAR_OUTPUT_BASE            (0x00007A80UL)
#define XBAR_CLB_OUTPUT_BASE        (0x00007BC0UL)

#define XBAR_O_CLB_INPUT            (XBAR_CLB_INPUT_BASE  - XBAR_INPUT_BASE )
#define XBAR_O_CLB_OUTPUT           (XBAR_CLB_OUTPUT_BASE - XBAR_OUTPUT_BASE)

#define XBAR_S_SRC_MUX_NUM(mux)     ( (mux) << 2)
#define XBAR_S_FLG_REG_NUM(reg)     ( (reg-1) << 5)

// Input XBAR
enum XBAR_Input
{
    XBAR_Input_1_HWSD   = 0x00,
    XBAR_Input_2        = 0x01,
    XBAR_Input_3        = 0x02,
    XBAR_Input_4        = 0x03,
    XBAR_Input_5        = 0x04,
    XBAR_Input_6_FWSD   = 0x05,    // Used by FW to force OST Trip on all OST-protected ePWM
    XBAR_Input_7        = 0x06,
    XBAR_Input_8        = 0x07,
    XBAR_Input_9        = 0x08,
    XBAR_Input_10       = 0x09,
    XBAR_Input_11       = 0x0A,
    XBAR_Input_12       = 0x0B,
    XBAR_Input_13       = 0x0C,
    XBAR_Input_14       = 0x0D,
    XBAR_Input_15       = 0x0E,
    XBAR_Input_16       = 0x0F,

    // CLB Input XBAR
    XBAR_Input_CLB_1    = 0x00 + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_2    = 0x01 + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_3    = 0x02 + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_4    = 0x03 + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_5    = 0x04 + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_6    = 0x05 + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_7    = 0x06 + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_8    = 0x07 + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_9    = 0x08 + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_10   = 0x09 + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_11   = 0x0A + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_12   = 0x0B + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_13   = 0x0C + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_14   = 0x0D + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_15   = 0x0E + XBAR_O_CLB_INPUT,
    XBAR_Input_CLB_16   = 0x0F + XBAR_O_CLB_INPUT
};


// ePWM XBAR (aka TRIP)
enum XBAR_Trip
{
    XBAR_Trip_4_OST = 0,    // ePWM XBAR4  (TRIP4), dedicated for OST
    XBAR_Trip_5     = 1,    // ePWM XBAR5  (TRIP5)
    XBAR_Trip_7     = 2,    // ePWM XBAR7  (TRIP7)
    XBAR_Trip_8     = 3,    // ePWM XBAR8  (TRIP8)
    XBAR_Trip_9     = 4,    // ePWM XBAR9  (TRIP9)
    XBAR_Trip_10    = 5,    // ePWM XBAR10 (TRIP10)
    XBAR_Trip_11    = 6,    // ePWM XBAR11 (TRIP11)
    XBAR_Trip_12    = 7     // ePWM XBAR12 (TRIP12)
};

// CLB XBAR
enum XBAR_CLB
{
    XBAR_CLB_0      = 0,
    XBAR_CLB_1      = 1,
    XBAR_CLB_2      = 2,
    XBAR_CLB_3      = 3,
    XBAR_CLB_4      = 4,
    XBAR_CLB_5      = 5,
    XBAR_CLB_6      = 6,
    XBAR_CLB_7      = 7
};

enum XBAR_Output
{
    XBAR_Output_1   = 0x00,
    XBAR_Output_2   = 0x01,
    XBAR_Output_3   = 0x02,
    XBAR_Output_4   = 0x03,
    XBAR_Output_5   = 0x04,
    XBAR_Output_6   = 0x05,
    XBAR_Output_7   = 0x06,
    XBAR_Output_8   = 0x07,

    // CLB Output XBAR, 0x140 offset is the difference between XBAR_CLB_OUTPUT_BASE and XBAR_OUTPUT_BASE
    XBAR_Output_CLB_1   = 0x00 + XBAR_O_CLB_OUTPUT,
    XBAR_Output_CLB_2   = 0x01 + XBAR_O_CLB_OUTPUT,
    XBAR_Output_CLB_3   = 0x02 + XBAR_O_CLB_OUTPUT,
    XBAR_Output_CLB_4   = 0x03 + XBAR_O_CLB_OUTPUT,
    XBAR_Output_CLB_5   = 0x04 + XBAR_O_CLB_OUTPUT,
    XBAR_Output_CLB_6   = 0x05 + XBAR_O_CLB_OUTPUT,
    XBAR_Output_CLB_7   = 0x06 + XBAR_O_CLB_OUTPUT,
    XBAR_Output_CLB_8   = 0x07 + XBAR_O_CLB_OUTPUT
};

enum XBAR_TripSrc
{
    XBAR_TripSrc_CMP1H              = XBAR_S_SRC_MUX_NUM( 0) | 0,
    XBAR_TripSrc_CMP1HL             = XBAR_S_SRC_MUX_NUM( 0) | 1,
    XBAR_TripSrc_ADCEVT_A1          = XBAR_S_SRC_MUX_NUM( 0) | 2,
    XBAR_TripSrc_eCAP1_Out          = XBAR_S_SRC_MUX_NUM( 0) | 3,
    XBAR_TripSrc_CMP1L              = XBAR_S_SRC_MUX_NUM( 1) | 0,
    XBAR_TripSrc_Input1             = XBAR_S_SRC_MUX_NUM( 1) | 1,
    XBAR_TripSrc_CLB1_Out12         = XBAR_S_SRC_MUX_NUM( 1) | 2,
    XBAR_TripSrc_ADCEVT_C1          = XBAR_S_SRC_MUX_NUM( 1) | 3,
    XBAR_TripSrc_CMP2H              = XBAR_S_SRC_MUX_NUM( 2) | 0,
    XBAR_TripSrc_CMP2HL             = XBAR_S_SRC_MUX_NUM( 2) | 1,
    XBAR_TripSrc_ADCEVT_A2          = XBAR_S_SRC_MUX_NUM( 2) | 2,
    XBAR_TripSrc_eCAP2_Out          = XBAR_S_SRC_MUX_NUM( 2) | 3,
    XBAR_TripSrc_CMP2L              = XBAR_S_SRC_MUX_NUM( 3) | 0,
    XBAR_TripSrc_Input2             = XBAR_S_SRC_MUX_NUM( 3) | 1,
    XBAR_TripSrc_CLB1_Out13         = XBAR_S_SRC_MUX_NUM( 3) | 2,
    XBAR_TripSrc_ADCEVT_C2          = XBAR_S_SRC_MUX_NUM( 3) | 3,
    XBAR_TripSrc_CMP3H              = XBAR_S_SRC_MUX_NUM( 4) | 0,
    XBAR_TripSrc_CMP3HL             = XBAR_S_SRC_MUX_NUM( 4) | 1,
    XBAR_TripSrc_ADCEVT_A3          = XBAR_S_SRC_MUX_NUM( 4) | 2,
    XBAR_TripSrc_eCAP3_Out          = XBAR_S_SRC_MUX_NUM( 4) | 3,
    XBAR_TripSrc_CMP3L              = XBAR_S_SRC_MUX_NUM( 5) | 0,
    XBAR_TripSrc_Input3             = XBAR_S_SRC_MUX_NUM( 5) | 1,
    XBAR_TripSrc_CLB2_Out12         = XBAR_S_SRC_MUX_NUM( 5) | 2,
    XBAR_TripSrc_ADCEVT_C3          = XBAR_S_SRC_MUX_NUM( 5) | 3,
    XBAR_TripSrc_CMP4H              = XBAR_S_SRC_MUX_NUM( 6) | 0,
    XBAR_TripSrc_CMP4HL             = XBAR_S_SRC_MUX_NUM( 6) | 1,
    XBAR_TripSrc_ADCEVT_A4          = XBAR_S_SRC_MUX_NUM( 6) | 2,
    XBAR_TripSrc_CMP4L              = XBAR_S_SRC_MUX_NUM( 7) | 0,
    XBAR_TripSrc_Input4             = XBAR_S_SRC_MUX_NUM( 7) | 1,
    XBAR_TripSrc_CLB2_Out13         = XBAR_S_SRC_MUX_NUM( 7) | 2,
    XBAR_TripSrc_ADCEVT_C4          = XBAR_S_SRC_MUX_NUM( 7) | 3,
    XBAR_TripSrc_ADCEVT_B1          = XBAR_S_SRC_MUX_NUM( 8) | 2,
    XBAR_TripSrc_Input5             = XBAR_S_SRC_MUX_NUM( 9) | 1,
    XBAR_TripSrc_CLB3_Out12         = XBAR_S_SRC_MUX_NUM( 9) | 2,
    XBAR_TripSrc_ADCEVT_B2          = XBAR_S_SRC_MUX_NUM(10) | 2,
    XBAR_TripSrc_Input6             = XBAR_S_SRC_MUX_NUM(11) | 1,
    XBAR_TripSrc_CLB3_Out13         = XBAR_S_SRC_MUX_NUM(11) | 2,
    XBAR_TripSrc_ADCEVT_B3          = XBAR_S_SRC_MUX_NUM(12) | 2,
    XBAR_TripSrc_ADCSOCAO           = XBAR_S_SRC_MUX_NUM(13) | 1,
    XBAR_TripSrc_CLB4_Out12         = XBAR_S_SRC_MUX_NUM(13) | 2,
    XBAR_TripSrc_ADCEVT_B4          = XBAR_S_SRC_MUX_NUM(14) | 2,
    XBAR_TripSrc_ExtSyncOut         = XBAR_S_SRC_MUX_NUM(14) | 3,
    XBAR_TripSrc_ADCSOCBO           = XBAR_S_SRC_MUX_NUM(15) | 1,
    XBAR_TripSrc_CLB4_Out13         = XBAR_S_SRC_MUX_NUM(15) | 2,
    XBAR_TripSrc_SD1FLT1_CEVT1      = XBAR_S_SRC_MUX_NUM(16) | 0,
    XBAR_TripSrc_SD1FLT1_CEVT1_OR_2 = XBAR_S_SRC_MUX_NUM(16) | 1,
    XBAR_TripSrc_SD1FLT1_CEVT2      = XBAR_S_SRC_MUX_NUM(17) | 0,
    XBAR_TripSrc_Input7             = XBAR_S_SRC_MUX_NUM(17) | 1,
    XBAR_TripSrc_CLBInput7          = XBAR_S_SRC_MUX_NUM(17) | 2,
    XBAR_TripSrc_CLAHalt            = XBAR_S_SRC_MUX_NUM(17) | 3,
    XBAR_TripSrc_SD1FLT2_CEVT1      = XBAR_S_SRC_MUX_NUM(18) | 0,
    XBAR_TripSrc_SD1FLT2_CEVT1_OR_2 = XBAR_S_SRC_MUX_NUM(18) | 1,
    XBAR_TripSrc_SD1FLT2_CEVT2      = XBAR_S_SRC_MUX_NUM(19) | 0,
    XBAR_TripSrc_Input8             = XBAR_S_SRC_MUX_NUM(19) | 1,
    XBAR_TripSrc_CLBInput8          = XBAR_S_SRC_MUX_NUM(19) | 2,
    XBAR_TripSrc_ERRORSTS           = XBAR_S_SRC_MUX_NUM(19) | 3,
    XBAR_TripSrc_SD1FLT3_CEVT1      = XBAR_S_SRC_MUX_NUM(20) | 0,
    XBAR_TripSrc_SD1FLT3_CEVT1_OR_2 = XBAR_S_SRC_MUX_NUM(20) | 1,
    XBAR_TripSrc_FSIRXA_TRIG1       = XBAR_S_SRC_MUX_NUM(20) | 3,
    XBAR_TripSrc_SD1FLT3_CEVT2      = XBAR_S_SRC_MUX_NUM(21) | 0,
    XBAR_TripSrc_Input9             = XBAR_S_SRC_MUX_NUM(21) | 1,
    XBAR_TripSrc_CLBInput9          = XBAR_S_SRC_MUX_NUM(21) | 2,
    XBAR_TripSrc_SD1FLT4_CEVT1      = XBAR_S_SRC_MUX_NUM(22) | 0,
    XBAR_TripSrc_SD1FLT4_CEVT1_OR_2 = XBAR_S_SRC_MUX_NUM(22) | 1,
    XBAR_TripSrc_SD1FLT4_CEVT2      = XBAR_S_SRC_MUX_NUM(23) | 0,
    XBAR_TripSrc_Input10            = XBAR_S_SRC_MUX_NUM(23) | 1,
    XBAR_TripSrc_CLBInput10         = XBAR_S_SRC_MUX_NUM(23) | 2,
    XBAR_TripSrc_SD2FLT1_CEVT1      = XBAR_S_SRC_MUX_NUM(24) | 0,
    XBAR_TripSrc_SD2FLT1_CEVT1_OR_2 = XBAR_S_SRC_MUX_NUM(24) | 1,
    XBAR_TripSrc_SD2FLT1_CEVT2      = XBAR_S_SRC_MUX_NUM(25) | 0,
    XBAR_TripSrc_Input11            = XBAR_S_SRC_MUX_NUM(25) | 1,
    XBAR_TripSrc_MCANA_FEVT0        = XBAR_S_SRC_MUX_NUM(25) | 2,
    XBAR_TripSrc_CLBInput11         = XBAR_S_SRC_MUX_NUM(25) | 3,
    XBAR_TripSrc_SD2FLT2_CEVT1      = XBAR_S_SRC_MUX_NUM(26) | 0,
    XBAR_TripSrc_SD2FLT2_CEVT1_OR_2 = XBAR_S_SRC_MUX_NUM(26) | 1,
    XBAR_TripSrc_SD2FLT2_CEVT2      = XBAR_S_SRC_MUX_NUM(27) | 0,
    XBAR_TripSrc_Input12            = XBAR_S_SRC_MUX_NUM(27) | 1,
    XBAR_TripSrc_MCANA_FEVT1        = XBAR_S_SRC_MUX_NUM(27) | 2,
    XBAR_TripSrc_CLBInput12         = XBAR_S_SRC_MUX_NUM(27) | 3,
    XBAR_TripSrc_SD2FLT3_CEVT1      = XBAR_S_SRC_MUX_NUM(28) | 0,
    XBAR_TripSrc_SD2FLT3_CEVT1_OR_2 = XBAR_S_SRC_MUX_NUM(28) | 1,
    XBAR_TripSrc_SD2FLT3_CEVT2      = XBAR_S_SRC_MUX_NUM(29) | 0,
    XBAR_TripSrc_Input13            = XBAR_S_SRC_MUX_NUM(29) | 1,
    XBAR_TripSrc_MCANA_FEVT2        = XBAR_S_SRC_MUX_NUM(29) | 2,
    XBAR_TripSrc_CLBInput13         = XBAR_S_SRC_MUX_NUM(29) | 3,
    XBAR_TripSrc_SD2FLT4_CEVT1      = XBAR_S_SRC_MUX_NUM(30) | 0,
    XBAR_TripSrc_SD2FLT4_CEVT1_OR_2 = XBAR_S_SRC_MUX_NUM(30) | 1,
    XBAR_TripSrc_SD2FLT4_CEVT2      = XBAR_S_SRC_MUX_NUM(31) | 0,
    XBAR_TripSrc_Input14            = XBAR_S_SRC_MUX_NUM(31) | 1,
    XBAR_TripSrc_ERRORSTS_ALT       = XBAR_S_SRC_MUX_NUM(31) | 2,
    XBAR_TripSrc_CLBInput14         = XBAR_S_SRC_MUX_NUM(31) | 3
};

enum XBAR_CLBSrc
{
    XBAR_CLBSrc_CMP1H               = XBAR_S_SRC_MUX_NUM( 0) | 0,
    XBAR_CLBSrc_CMP1HL              = XBAR_S_SRC_MUX_NUM( 0) | 1,
    XBAR_CLBSrc_ADCEVT_A1           = XBAR_S_SRC_MUX_NUM( 0) | 2,
    XBAR_CLBSrc_eCAP1_Out           = XBAR_S_SRC_MUX_NUM( 0) | 3,
    XBAR_CLBSrc_CMP1L               = XBAR_S_SRC_MUX_NUM( 1) | 0,
    XBAR_CLBSrc_Input1              = XBAR_S_SRC_MUX_NUM( 1) | 1,
    XBAR_CLBSrc_CLB1_Out12          = XBAR_S_SRC_MUX_NUM( 1) | 2,
    XBAR_CLBSrc_ADCEVT_C1           = XBAR_S_SRC_MUX_NUM( 1) | 3,
    XBAR_CLBSrc_CMP2H               = XBAR_S_SRC_MUX_NUM( 2) | 0,
    XBAR_CLBSrc_CMP2HL              = XBAR_S_SRC_MUX_NUM( 2) | 1,
    XBAR_CLBSrc_ADCEVT_A2           = XBAR_S_SRC_MUX_NUM( 2) | 2,
    XBAR_CLBSrc_eCAP2_Out           = XBAR_S_SRC_MUX_NUM( 2) | 3,
    XBAR_CLBSrc_CMP2L               = XBAR_S_SRC_MUX_NUM( 3) | 0,
    XBAR_CLBSrc_Input2              = XBAR_S_SRC_MUX_NUM( 3) | 1,
    XBAR_CLBSrc_CLB1_Out13          = XBAR_S_SRC_MUX_NUM( 3) | 2,
    XBAR_CLBSrc_ADCEVT_C2           = XBAR_S_SRC_MUX_NUM( 3) | 3,
    XBAR_CLBSrc_CMP3H               = XBAR_S_SRC_MUX_NUM( 4) | 0,
    XBAR_CLBSrc_CMP3HL              = XBAR_S_SRC_MUX_NUM( 4) | 1,
    XBAR_CLBSrc_ADCEVT_A3           = XBAR_S_SRC_MUX_NUM( 4) | 2,
    XBAR_CLBSrc_eCAP3_Out           = XBAR_S_SRC_MUX_NUM( 4) | 3,
    XBAR_CLBSrc_CMP3L               = XBAR_S_SRC_MUX_NUM( 5) | 0,
    XBAR_CLBSrc_Input3              = XBAR_S_SRC_MUX_NUM( 5) | 1,
    XBAR_CLBSrc_CLB2_Out12          = XBAR_S_SRC_MUX_NUM( 5) | 2,
    XBAR_CLBSrc_ADCEVT_C3           = XBAR_S_SRC_MUX_NUM( 5) | 3,
    XBAR_CLBSrc_CMP4H               = XBAR_S_SRC_MUX_NUM( 6) | 0,
    XBAR_CLBSrc_CMP4HL              = XBAR_S_SRC_MUX_NUM( 6) | 1,
    XBAR_CLBSrc_ADCEVT_A4           = XBAR_S_SRC_MUX_NUM( 6) | 2,
    XBAR_CLBSrc_CMP4L               = XBAR_S_SRC_MUX_NUM( 7) | 0,
    XBAR_CLBSrc_Input4              = XBAR_S_SRC_MUX_NUM( 7) | 1,
    XBAR_CLBSrc_CLB2_Out13          = XBAR_S_SRC_MUX_NUM( 7) | 2,
    XBAR_CLBSrc_ADCEVT_C4           = XBAR_S_SRC_MUX_NUM( 7) | 3,
    XBAR_CLBSrc_ADCEVT_B1           = XBAR_S_SRC_MUX_NUM( 8) | 2,
    XBAR_CLBSrc_Input5              = XBAR_S_SRC_MUX_NUM( 9) | 1,
    XBAR_CLBSrc_CLB3_Out12          = XBAR_S_SRC_MUX_NUM( 9) | 2,
    XBAR_CLBSrc_ADCEVT_B2           = XBAR_S_SRC_MUX_NUM(10) | 2,
    XBAR_CLBSrc_Input6              = XBAR_S_SRC_MUX_NUM(11) | 1,
    XBAR_CLBSrc_CLB3_Out13          = XBAR_S_SRC_MUX_NUM(11) | 2,
    XBAR_CLBSrc_ADCEVT_B3           = XBAR_S_SRC_MUX_NUM(12) | 2,
    XBAR_CLBSrc_ADCSOCAO            = XBAR_S_SRC_MUX_NUM(13) | 1,
    XBAR_CLBSrc_CLB4_Out12          = XBAR_S_SRC_MUX_NUM(13) | 2,
    XBAR_CLBSrc_ADCEVT_B4           = XBAR_S_SRC_MUX_NUM(14) | 2,
    XBAR_CLBSrc_ExtSyncOut          = XBAR_S_SRC_MUX_NUM(14) | 3,
    XBAR_CLBSrc_ADCSOCBO            = XBAR_S_SRC_MUX_NUM(15) | 1,
    XBAR_CLBSrc_CLB4_Out13          = XBAR_S_SRC_MUX_NUM(15) | 2,
    XBAR_CLBSrc_SD1FLT1_CEVT1       = XBAR_S_SRC_MUX_NUM(16) | 0,
    XBAR_CLBSrc_SD1FLT1_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(16) | 1,
    XBAR_CLBSrc_SD1FLT1_COMPZ       = XBAR_S_SRC_MUX_NUM(16) | 2,
    XBAR_CLBSrc_SD1FLT1_DRINT       = XBAR_S_SRC_MUX_NUM(16) | 3,
    XBAR_CLBSrc_SD1FLT1_CEVT2       = XBAR_S_SRC_MUX_NUM(17) | 0,
    XBAR_CLBSrc_Input7              = XBAR_S_SRC_MUX_NUM(17) | 1,
    XBAR_CLBSrc_CLAHalt             = XBAR_S_SRC_MUX_NUM(17) | 3,
    XBAR_CLBSrc_SD1FLT2_CEVT1       = XBAR_S_SRC_MUX_NUM(18) | 0,
    XBAR_CLBSrc_SD1FLT2_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(18) | 1,
    XBAR_CLBSrc_SD1FLT2_COMPZ       = XBAR_S_SRC_MUX_NUM(18) | 2,
    XBAR_CLBSrc_SD1FLT2_DRINT       = XBAR_S_SRC_MUX_NUM(18) | 3,
    XBAR_CLBSrc_SD1FLT2_CEVT2       = XBAR_S_SRC_MUX_NUM(19) | 0,
    XBAR_CLBSrc_Input8              = XBAR_S_SRC_MUX_NUM(19) | 1,
    XBAR_CLBSrc_ErrorSts            = XBAR_S_SRC_MUX_NUM(19) | 3,
    XBAR_CLBSrc_SD1FLT3_CEVT1       = XBAR_S_SRC_MUX_NUM(20) | 0,
    XBAR_CLBSrc_SD1FLT3_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(20) | 1,
    XBAR_CLBSrc_SD1FLT3_COMPZ       = XBAR_S_SRC_MUX_NUM(20) | 2,
    XBAR_CLBSrc_SD1FLT3_DRINT       = XBAR_S_SRC_MUX_NUM(20) | 3,
    XBAR_CLBSrc_SD1FLT3_CEVT2       = XBAR_S_SRC_MUX_NUM(21) | 0,
    XBAR_CLBSrc_Input9              = XBAR_S_SRC_MUX_NUM(21) | 1,
    XBAR_CLBSrc_SD1FLT4_CEVT1       = XBAR_S_SRC_MUX_NUM(22) | 0,
    XBAR_CLBSrc_SD1FLT4_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(22) | 1,
    XBAR_CLBSrc_SD1FLT4_COMPZ       = XBAR_S_SRC_MUX_NUM(22) | 2,
    XBAR_CLBSrc_SD1FLT4_DRINT       = XBAR_S_SRC_MUX_NUM(22) | 3,
    XBAR_CLBSrc_SD1FLT4_CEVT2       = XBAR_S_SRC_MUX_NUM(23) | 0,
    XBAR_CLBSrc_Input10             = XBAR_S_SRC_MUX_NUM(23) | 1,
    XBAR_CLBSrc_SD2FLT1_CEVT1       = XBAR_S_SRC_MUX_NUM(24) | 0,
    XBAR_CLBSrc_SD2FLT1_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(24) | 1,
    XBAR_CLBSrc_SD2FLT1_COMPZ       = XBAR_S_SRC_MUX_NUM(24) | 2,
    XBAR_CLBSrc_SD2FLT1_DRINT       = XBAR_S_SRC_MUX_NUM(24) | 3,
    XBAR_CLBSrc_SD2FLT1_CEVT2       = XBAR_S_SRC_MUX_NUM(25) | 0,
    XBAR_CLBSrc_Input11             = XBAR_S_SRC_MUX_NUM(25) | 1,
    XBAR_CLBSrc_MCANA_FEVT0         = XBAR_S_SRC_MUX_NUM(25) | 2,
    XBAR_CLBSrc_SD2FLT2_CEVT1       = XBAR_S_SRC_MUX_NUM(26) | 0,
    XBAR_CLBSrc_SD2FLT2_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(26) | 1,
    XBAR_CLBSrc_SD2FLT2_COMPZ       = XBAR_S_SRC_MUX_NUM(26) | 2,
    XBAR_CLBSrc_SD2FLT2_DRINT       = XBAR_S_SRC_MUX_NUM(26) | 3,
    XBAR_CLBSrc_SD2FLT2_CEVT2       = XBAR_S_SRC_MUX_NUM(27) | 0,
    XBAR_CLBSrc_Input12             = XBAR_S_SRC_MUX_NUM(27) | 1,
    XBAR_CLBSrc_MCANA_FEVT1         = XBAR_S_SRC_MUX_NUM(27) | 2,
    XBAR_CLBSrc_SD2FLT3_CEVT1       = XBAR_S_SRC_MUX_NUM(28) | 0,
    XBAR_CLBSrc_SD2FLT3_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(28) | 1,
    XBAR_CLBSrc_SD2FLT3_COMPZ       = XBAR_S_SRC_MUX_NUM(28) | 2,
    XBAR_CLBSrc_SD2FLT3_DRINT       = XBAR_S_SRC_MUX_NUM(28) | 3,
    XBAR_CLBSrc_SD2FLT3_CEVT2       = XBAR_S_SRC_MUX_NUM(29) | 0,
    XBAR_CLBSrc_Input13             = XBAR_S_SRC_MUX_NUM(29) | 1,
    XBAR_CLBSrc_MCANA_FEVT2         = XBAR_S_SRC_MUX_NUM(29) | 2,
    XBAR_CLBSrc_SD2FLT4_CEVT1       = XBAR_S_SRC_MUX_NUM(30) | 0,
    XBAR_CLBSrc_SD2FLT4_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(30) | 1,
    XBAR_CLBSrc_SD2FLT4_COMPZ       = XBAR_S_SRC_MUX_NUM(30) | 2,
    XBAR_CLBSrc_SD2FLT4_DRINT       = XBAR_S_SRC_MUX_NUM(30) | 3,
    XBAR_CLBSrc_SD2FLT4_CEVT2       = XBAR_S_SRC_MUX_NUM(31) | 0,
    XBAR_CLBSrc_Input14             = XBAR_S_SRC_MUX_NUM(31) | 1,
    XBAR_CLBSrc_ErrorStsAlt         = XBAR_S_SRC_MUX_NUM(31) | 2
};

enum XBAR_OutSrc
{
    XBAR_OutSrc_CMP1H_Out           = XBAR_S_SRC_MUX_NUM( 0) | 0,
    XBAR_OutSrc_CMP1HL_Out          = XBAR_S_SRC_MUX_NUM( 0) | 1,
    XBAR_OutSrc_ADCEVT_A1           = XBAR_S_SRC_MUX_NUM( 0) | 2,
    XBAR_OutSrc_eCAP1_Out           = XBAR_S_SRC_MUX_NUM( 0) | 3,
    XBAR_OutSrc_CMP1L_Out           = XBAR_S_SRC_MUX_NUM( 1) | 0,
    XBAR_OutSrc_Input1              = XBAR_S_SRC_MUX_NUM( 1) | 1,
    XBAR_OutSrc_CLB1_Out12          = XBAR_S_SRC_MUX_NUM( 1) | 2,
    XBAR_OutSrc_ADCEVT_C1           = XBAR_S_SRC_MUX_NUM( 1) | 3,
    XBAR_OutSrc_CMP2H_Out           = XBAR_S_SRC_MUX_NUM( 2) | 0,
    XBAR_OutSrc_CMP2HL_Out          = XBAR_S_SRC_MUX_NUM( 2) | 1,
    XBAR_OutSrc_ADCEVT_A2           = XBAR_S_SRC_MUX_NUM( 2) | 2,
    XBAR_OutSrc_eCAP2_Out           = XBAR_S_SRC_MUX_NUM( 2) | 3,
    XBAR_OutSrc_CMP2L_Out           = XBAR_S_SRC_MUX_NUM( 3) | 0,
    XBAR_OutSrc_Input2              = XBAR_S_SRC_MUX_NUM( 3) | 1,
    XBAR_OutSrc_CLB1_Out13          = XBAR_S_SRC_MUX_NUM( 3) | 2,
    XBAR_OutSrc_ADCEVT_C2           = XBAR_S_SRC_MUX_NUM( 3) | 3,
    XBAR_OutSrc_CMP3H_Out           = XBAR_S_SRC_MUX_NUM( 4) | 0,
    XBAR_OutSrc_CMP3HL_Out          = XBAR_S_SRC_MUX_NUM( 4) | 1,
    XBAR_OutSrc_ADCEVT_A3           = XBAR_S_SRC_MUX_NUM( 4) | 2,
    XBAR_OutSrc_eCAP3_Out           = XBAR_S_SRC_MUX_NUM( 4) | 3,
    XBAR_OutSrc_CMP3L_Out           = XBAR_S_SRC_MUX_NUM( 5) | 0,
    XBAR_OutSrc_Input3              = XBAR_S_SRC_MUX_NUM( 5) | 1,
    XBAR_OutSrc_CLB2_Out12          = XBAR_S_SRC_MUX_NUM( 5) | 2,
    XBAR_OutSrc_ADCEVT_C3           = XBAR_S_SRC_MUX_NUM( 5) | 3,
    XBAR_OutSrc_CMP4H_Out           = XBAR_S_SRC_MUX_NUM( 6) | 0,
    XBAR_OutSrc_CMP4HL_Out          = XBAR_S_SRC_MUX_NUM( 6) | 1,
    XBAR_OutSrc_ADCEVT_A4           = XBAR_S_SRC_MUX_NUM( 6) | 2,
    XBAR_OutSrc_CMP4L_Out           = XBAR_S_SRC_MUX_NUM( 7) | 0,
    XBAR_OutSrc_Input4              = XBAR_S_SRC_MUX_NUM( 7) | 1,
    XBAR_OutSrc_CLB2_Out13          = XBAR_S_SRC_MUX_NUM( 7) | 2,
    XBAR_OutSrc_ADCEVT_C4           = XBAR_S_SRC_MUX_NUM( 7) | 3,
    XBAR_OutSrc_ADCEVT_B1           = XBAR_S_SRC_MUX_NUM( 8) | 2,
    XBAR_OutSrc_Input5              = XBAR_S_SRC_MUX_NUM( 9) | 1,
    XBAR_OutSrc_CLB3_Out12          = XBAR_S_SRC_MUX_NUM( 9) | 2,
    XBAR_OutSrc_ADCEVT_B2           = XBAR_S_SRC_MUX_NUM(10) | 2,
    XBAR_OutSrc_Input6              = XBAR_S_SRC_MUX_NUM(11) | 1,
    XBAR_OutSrc_CLB3_Out13          = XBAR_S_SRC_MUX_NUM(11) | 2,
    XBAR_OutSrc_ADCEVT_B3           = XBAR_S_SRC_MUX_NUM(12) | 2,
    XBAR_OutSrc_ADCSOCAO            = XBAR_S_SRC_MUX_NUM(13) | 1,
    XBAR_OutSrc_CLB4_Out12          = XBAR_S_SRC_MUX_NUM(13) | 2,
    XBAR_OutSrc_ADCEVT_B4           = XBAR_S_SRC_MUX_NUM(14) | 2,
    XBAR_OutSrc_ExtSyncOut          = XBAR_S_SRC_MUX_NUM(14) | 3,
    XBAR_OutSrc_ADCSOCBO            = XBAR_S_SRC_MUX_NUM(15) | 1,
    XBAR_OutSrc_CLB4_Out13          = XBAR_S_SRC_MUX_NUM(15) | 2,
    XBAR_OutSrc_SD1FLT1_CEVT1       = XBAR_S_SRC_MUX_NUM(16) | 0,
    XBAR_OutSrc_SD1FLT1_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(16) | 1,
    XBAR_OutSrc_SD1FLT1_CEVT2       = XBAR_S_SRC_MUX_NUM(17) | 0,
    XBAR_OutSrc_CLAHalt             = XBAR_S_SRC_MUX_NUM(17) | 3,
    XBAR_OutSrc_SD1FLT2_CEVT1       = XBAR_S_SRC_MUX_NUM(18) | 0,
    XBAR_OutSrc_SD1FLT2_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(18) | 1,
    XBAR_OutSrc_SD1FLT2_CEVT2       = XBAR_S_SRC_MUX_NUM(19) | 0,
    XBAR_OutSrc_ErrorSts            = XBAR_S_SRC_MUX_NUM(19) | 3,
    XBAR_OutSrc_SD1FLT3_CEVT1       = XBAR_S_SRC_MUX_NUM(20) | 0,
    XBAR_OutSrc_SD1FLT3_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(20) | 1,
    XBAR_OutSrc_SD1FLT3_CEVT2       = XBAR_S_SRC_MUX_NUM(21) | 0,
    XBAR_OutSrc_FSIRXA_TRIG2        = XBAR_S_SRC_MUX_NUM(21) | 3,
    XBAR_OutSrc_SD1FLT4_CEVT1       = XBAR_S_SRC_MUX_NUM(22) | 0,
    XBAR_OutSrc_SD1FLT4_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(22) | 1,
    XBAR_OutSrc_SD1FLT4_CEVT2       = XBAR_S_SRC_MUX_NUM(23) | 0,
    XBAR_OutSrc_SD2FLT1_CEVT1       = XBAR_S_SRC_MUX_NUM(24) | 0,
    XBAR_OutSrc_SD2FLT1_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(24) | 1,
    XBAR_OutSrc_SD2FLT1_CEVT2       = XBAR_S_SRC_MUX_NUM(25) | 0,
    XBAR_OutSrc_SD2FLT2_CEVT1       = XBAR_S_SRC_MUX_NUM(26) | 0,
    XBAR_OutSrc_SD2FLT2_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(26) | 1,
    XBAR_OutSrc_SD2FLT2_CEVT2       = XBAR_S_SRC_MUX_NUM(27) | 0,
    XBAR_OutSrc_SD2FLT3_CEVT1       = XBAR_S_SRC_MUX_NUM(28) | 0,
    XBAR_OutSrc_SD2FLT3_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(28) | 1,
    XBAR_OutSrc_SD2FLT3_CEVT2       = XBAR_S_SRC_MUX_NUM(29) | 0,
    XBAR_OutSrc_SD2FLT4_CEVT1       = XBAR_S_SRC_MUX_NUM(30) | 0,
    XBAR_OutSrc_SD2FLT4_CEVT1_OR_2  = XBAR_S_SRC_MUX_NUM(30) | 1,
    XBAR_OutSrc_EPG1OUT0            = XBAR_S_SRC_MUX_NUM(30) | 3,
    XBAR_OutSrc_SD2FLT4_CEVT2       = XBAR_S_SRC_MUX_NUM(31) | 0,
    XBAR_OutSrc_ErrorStsAlt         = XBAR_S_SRC_MUX_NUM(31) | 2,
    XBAR_OutSrc_EPG1OUT1            = XBAR_S_SRC_MUX_NUM(31) | 3,

    XBAR_OutSrc_CLB_CLB1_Out0       = XBAR_S_SRC_MUX_NUM(0)  | 0,
    XBAR_OutSrc_CLB_Output1         = XBAR_S_SRC_MUX_NUM(0)  | 3,
    XBAR_OutSrc_CLB_CLB1_Out1       = XBAR_S_SRC_MUX_NUM(1)  | 0,
    XBAR_OutSrc_CLB_Output2         = XBAR_S_SRC_MUX_NUM(1)  | 3,
    XBAR_OutSrc_CLB_CLB1_Out2       = XBAR_S_SRC_MUX_NUM(2)  | 0,
    XBAR_OutSrc_CLB_CLB1_Out3       = XBAR_S_SRC_MUX_NUM(3)  | 0,
    XBAR_OutSrc_CLB_CLB1_Out4       = XBAR_S_SRC_MUX_NUM(4)  | 0,
    XBAR_OutSrc_CLB_CLB1_Out5       = XBAR_S_SRC_MUX_NUM(5)  | 0,
    XBAR_OutSrc_CLB_CLB1_Out6       = XBAR_S_SRC_MUX_NUM(6)  | 0,
    XBAR_OutSrc_CLB_CLB1_Out7       = XBAR_S_SRC_MUX_NUM(7)  | 0,
    XBAR_OutSrc_CLB_CLB2_Out0       = XBAR_S_SRC_MUX_NUM(8)  | 0,
    XBAR_OutSrc_CLB_Output3         = XBAR_S_SRC_MUX_NUM(8)  | 3,
    XBAR_OutSrc_CLB_CLB2_Out1       = XBAR_S_SRC_MUX_NUM(9)  | 0,
    XBAR_OutSrc_CLB_Output4         = XBAR_S_SRC_MUX_NUM(9)  | 3,
    XBAR_OutSrc_CLB_CLB2_Out2       = XBAR_S_SRC_MUX_NUM(10) | 0,
    XBAR_OutSrc_CLB_CLB2_Out3       = XBAR_S_SRC_MUX_NUM(11) | 0,
    XBAR_OutSrc_CLB_CLB2_Out4       = XBAR_S_SRC_MUX_NUM(12) | 0,
    XBAR_OutSrc_CLB_CLB2_Out5       = XBAR_S_SRC_MUX_NUM(13) | 0,
    XBAR_OutSrc_CLB_CLB2_Out6       = XBAR_S_SRC_MUX_NUM(14) | 0,
    XBAR_OutSrc_CLB_CLB2_Out7       = XBAR_S_SRC_MUX_NUM(15) | 0,
    XBAR_OutSrc_CLB_CLB3_Out0       = XBAR_S_SRC_MUX_NUM(16) | 0,
    XBAR_OutSrc_CLB_Output5         = XBAR_S_SRC_MUX_NUM(16) | 3,
    XBAR_OutSrc_CLB_CLB3_Out1       = XBAR_S_SRC_MUX_NUM(17) | 0,
    XBAR_OutSrc_CLB_Output6         = XBAR_S_SRC_MUX_NUM(17) | 3,
    XBAR_OutSrc_CLB_CLB3_Out2       = XBAR_S_SRC_MUX_NUM(18) | 0,
    XBAR_OutSrc_CLB_CLB3_Out3       = XBAR_S_SRC_MUX_NUM(19) | 0,
    XBAR_OutSrc_CLB_CLB3_Out4       = XBAR_S_SRC_MUX_NUM(20) | 0,
    XBAR_OutSrc_CLB_CLB3_Out5       = XBAR_S_SRC_MUX_NUM(21) | 0,
    XBAR_OutSrc_CLB_CLB3_Out6       = XBAR_S_SRC_MUX_NUM(22) | 0,
    XBAR_OutSrc_CLB_CLB3_Out7       = XBAR_S_SRC_MUX_NUM(23) | 0,
    XBAR_OutSrc_CLB_CLB4_Out0       = XBAR_S_SRC_MUX_NUM(24) | 0,
    XBAR_OutSrc_CLB_Output7         = XBAR_S_SRC_MUX_NUM(24) | 3,
    XBAR_OutSrc_CLB_CLB4_Out1       = XBAR_S_SRC_MUX_NUM(25) | 0,
    XBAR_OutSrc_CLB_Output8         = XBAR_S_SRC_MUX_NUM(25) | 3,
    XBAR_OutSrc_CLB_CLB4_Out2       = XBAR_S_SRC_MUX_NUM(26) | 0,
    XBAR_OutSrc_CLB_CLB4_Out3       = XBAR_S_SRC_MUX_NUM(27) | 0,
    XBAR_OutSrc_CLB_CLB4_Out4       = XBAR_S_SRC_MUX_NUM(28) | 0,
    XBAR_OutSrc_CLB_CLB4_Out5       = XBAR_S_SRC_MUX_NUM(29) | 0,
    XBAR_OutSrc_CLB_CLB4_Out6       = XBAR_S_SRC_MUX_NUM(30) | 0,
    XBAR_OutSrc_CLB_EPG1_Out2       = XBAR_S_SRC_MUX_NUM(30) | 3,
    XBAR_OutSrc_CLB_CLB4_Out7       = XBAR_S_SRC_MUX_NUM(31) | 0,
    XBAR_OutSrc_CLB_EPG1_Out3       = XBAR_S_SRC_MUX_NUM(31) | 3
};

enum XBAR_Flag
{
    XBAR_Flag_CMP1L_Trip    = XBAR_S_FLG_REG_NUM(1) |  0,
    XBAR_Flag_CMP1H_Trip    = XBAR_S_FLG_REG_NUM(1) |  1,
    XBAR_Flag_CMP2L_Trip    = XBAR_S_FLG_REG_NUM(1) |  2,
    XBAR_Flag_CMP2H_Trip    = XBAR_S_FLG_REG_NUM(1) |  3,
    XBAR_Flag_CMP3L_Trip    = XBAR_S_FLG_REG_NUM(1) |  4,
    XBAR_Flag_CMP3H_Trip    = XBAR_S_FLG_REG_NUM(1) |  5,
    XBAR_Flag_CMP4L_Trip    = XBAR_S_FLG_REG_NUM(1) |  6,
    XBAR_Flag_CMP4H_Trip    = XBAR_S_FLG_REG_NUM(1) |  7,
    XBAR_Flag_CMP1L_Out     = XBAR_S_FLG_REG_NUM(1) | 16,
    XBAR_Flag_CMP1H_Out     = XBAR_S_FLG_REG_NUM(1) | 17,
    XBAR_Flag_CMP2L_Out     = XBAR_S_FLG_REG_NUM(1) | 18,
    XBAR_Flag_CMP2H_Out     = XBAR_S_FLG_REG_NUM(1) | 19,
    XBAR_Flag_CMP3L_Out     = XBAR_S_FLG_REG_NUM(1) | 20,
    XBAR_Flag_CMP3H_Out     = XBAR_S_FLG_REG_NUM(1) | 21,
    XBAR_Flag_CMP4L_Out     = XBAR_S_FLG_REG_NUM(1) | 22,
    XBAR_Flag_CMP4H_Out     = XBAR_S_FLG_REG_NUM(1) | 23,

    XBAR_Flag_Input1_HWSD   = XBAR_S_FLG_REG_NUM(2) |  0,
    XBAR_Flag_Input2        = XBAR_S_FLG_REG_NUM(2) |  1,
    XBAR_Flag_Input3        = XBAR_S_FLG_REG_NUM(2) |  2,
    XBAR_Flag_Input4        = XBAR_S_FLG_REG_NUM(2) |  3,
    XBAR_Flag_Input5        = XBAR_S_FLG_REG_NUM(2) |  4,
    XBAR_Flag_Input6_FWSD   = XBAR_S_FLG_REG_NUM(2) |  5,
    XBAR_Flag_ADCSOCA       = XBAR_S_FLG_REG_NUM(2) |  6,
    XBAR_Flag_ADCSOCB       = XBAR_S_FLG_REG_NUM(2) |  7,
    XBAR_Flag_Input7        = XBAR_S_FLG_REG_NUM(2) |  8,
    XBAR_Flag_Input8        = XBAR_S_FLG_REG_NUM(2) |  9,
    XBAR_Flag_Input9        = XBAR_S_FLG_REG_NUM(2) | 10,
    XBAR_Flag_Input10       = XBAR_S_FLG_REG_NUM(2) | 11,
    XBAR_Flag_Input11       = XBAR_S_FLG_REG_NUM(2) | 12,
    XBAR_Flag_Input12       = XBAR_S_FLG_REG_NUM(2) | 13,
    XBAR_Flag_Input13       = XBAR_S_FLG_REG_NUM(2) | 14,
    XBAR_Flag_Input14       = XBAR_S_FLG_REG_NUM(2) | 15,
    XBAR_Flag_eCAP1         = XBAR_S_FLG_REG_NUM(2) | 16,
    XBAR_Flag_eCAP2         = XBAR_S_FLG_REG_NUM(2) | 17,
    XBAR_Flag_eCAP3         = XBAR_S_FLG_REG_NUM(2) | 18,
    XBAR_Flag_SyncOut       = XBAR_S_FLG_REG_NUM(2) | 22,
    XBAR_Flag_ADCEVT_A1     = XBAR_S_FLG_REG_NUM(2) | 23,
    XBAR_Flag_ADCEVT_A2     = XBAR_S_FLG_REG_NUM(2) | 24,
    XBAR_Flag_ADCEVT_A3     = XBAR_S_FLG_REG_NUM(2) | 25,
    XBAR_Flag_ADCEVT_A4     = XBAR_S_FLG_REG_NUM(2) | 26,
    XBAR_Flag_ADCEVT_B1     = XBAR_S_FLG_REG_NUM(2) | 27,
    XBAR_Flag_ADCEVT_B2     = XBAR_S_FLG_REG_NUM(2) | 28,
    XBAR_Flag_ADCEVT_B3     = XBAR_S_FLG_REG_NUM(2) | 29,
    XBAR_Flag_ADCEVT_B4     = XBAR_S_FLG_REG_NUM(2) | 30,
    XBAR_Flag_ADCEVT_C1     = XBAR_S_FLG_REG_NUM(2) | 31,

    XBAR_Flag_ADCEVT_C2     = XBAR_S_FLG_REG_NUM(3) |  0,
    XBAR_Flag_ADCEVT_C3     = XBAR_S_FLG_REG_NUM(3) |  1,
    XBAR_Flag_ADCEVT_C4     = XBAR_S_FLG_REG_NUM(3) |  2,
    XBAR_Flag_SD1FLT1_COMPL = XBAR_S_FLG_REG_NUM(3) |  7,
    XBAR_Flag_SD1FLT1_COMPH = XBAR_S_FLG_REG_NUM(3) |  8,
    XBAR_Flag_SD1FLT2_COMPL = XBAR_S_FLG_REG_NUM(3) |  9,
    XBAR_Flag_SD1FLT2_COMPH = XBAR_S_FLG_REG_NUM(3) | 10,
    XBAR_Flag_SD1FLT3_COMPL = XBAR_S_FLG_REG_NUM(3) | 11,
    XBAR_Flag_SD1FLT3_COMPH = XBAR_S_FLG_REG_NUM(3) | 12,
    XBAR_Flag_SD1FLT4_COMPL = XBAR_S_FLG_REG_NUM(3) | 13,
    XBAR_Flag_SD1FLT4_COMPH = XBAR_S_FLG_REG_NUM(3) | 14,
    XBAR_Flag_SD2FLT1_COMPL = XBAR_S_FLG_REG_NUM(3) | 15,
    XBAR_Flag_SD2FLT1_COMPH = XBAR_S_FLG_REG_NUM(3) | 16,
    XBAR_Flag_SD2FLT2_COMPL = XBAR_S_FLG_REG_NUM(3) | 17,
    XBAR_Flag_SD2FLT2_COMPH = XBAR_S_FLG_REG_NUM(3) | 18,
    XBAR_Flag_SD2FLT3_COMPL = XBAR_S_FLG_REG_NUM(3) | 19,
    XBAR_Flag_SD2FLT3_COMPH = XBAR_S_FLG_REG_NUM(3) | 20,
    XBAR_Flag_SD2FLT4_COMPL = XBAR_S_FLG_REG_NUM(3) | 21,
    XBAR_Flag_SD2FLT4_COMPH = XBAR_S_FLG_REG_NUM(3) | 22,
    XBAR_Flag_SD1FLT1_COMPZ = XBAR_S_FLG_REG_NUM(3) | 24,
    XBAR_Flag_SD1FLT1_DRINT = XBAR_S_FLG_REG_NUM(3) | 25,
    XBAR_Flag_SD1FLT2_COMPZ = XBAR_S_FLG_REG_NUM(3) | 26,
    XBAR_Flag_SD1FLT2_DRINT = XBAR_S_FLG_REG_NUM(3) | 27,
    XBAR_Flag_SD1FLT3_COMPZ = XBAR_S_FLG_REG_NUM(3) | 28,
    XBAR_Flag_SD1FLT3_DRINT = XBAR_S_FLG_REG_NUM(3) | 29,
    XBAR_Flag_SD1FLT4_COMPZ = XBAR_S_FLG_REG_NUM(3) | 30,
    XBAR_Flag_SD1FLT4_DRINT = XBAR_S_FLG_REG_NUM(3) | 31,

    XBAR_Flag_SD2FLT1_COMPZ = XBAR_S_FLG_REG_NUM(4) |  0,
    XBAR_Flag_SD2FLT1_DRINT = XBAR_S_FLG_REG_NUM(4) |  1,
    XBAR_Flag_SD2FLT2_COMPZ = XBAR_S_FLG_REG_NUM(4) |  2,
    XBAR_Flag_SD2FLT2_DRINT = XBAR_S_FLG_REG_NUM(4) |  3,
    XBAR_Flag_SD2FLT3_COMPZ = XBAR_S_FLG_REG_NUM(4) |  4,
    XBAR_Flag_SD2FLT3_DRINT = XBAR_S_FLG_REG_NUM(4) |  5,
    XBAR_Flag_SD2FLT4_COMPZ = XBAR_S_FLG_REG_NUM(4) |  6,
    XBAR_Flag_SD2FLT4_DRINT = XBAR_S_FLG_REG_NUM(4) |  7,
    XBAR_Flag_MCANA_FEVT0   = XBAR_S_FLG_REG_NUM(4) |  9,
    XBAR_Flag_MCANA_FEVT1   = XBAR_S_FLG_REG_NUM(4) | 10,
    XBAR_Flag_MCANA_FEVT2   = XBAR_S_FLG_REG_NUM(4) | 11,
    XBAR_Flag_CLB1_4_1      = XBAR_S_FLG_REG_NUM(4) | 16,
    XBAR_Flag_CLB1_5_1      = XBAR_S_FLG_REG_NUM(4) | 17,
    XBAR_Flag_CLB2_4_1      = XBAR_S_FLG_REG_NUM(4) | 18,
    XBAR_Flag_CLB2_5_1      = XBAR_S_FLG_REG_NUM(4) | 19,
    XBAR_Flag_CLB3_4_1      = XBAR_S_FLG_REG_NUM(4) | 20,
    XBAR_Flag_CLB3_5_1      = XBAR_S_FLG_REG_NUM(4) | 21,
    XBAR_Flag_CLB4_4_1      = XBAR_S_FLG_REG_NUM(4) | 22,
    XBAR_Flag_CLB4_5_1      = XBAR_S_FLG_REG_NUM(4) | 23,
    XBAR_Flag_Error         = XBAR_S_FLG_REG_NUM(4) | 28,
    XBAR_Flag_CLAHalt       = XBAR_S_FLG_REG_NUM(4) | 31
};

#endif /* SUPPORT_XBAR_H_ */
