#ifndef SUPPORT_ANALOG_H_
#define SUPPORT_ANALOG_H_

#include "support_adc.h"
#include "support_cmpss.h"
#include "gpio.h"

#define ADC_TYPE_DEVICE     5

#define ANALOG_BASE         (0x0005D700UL)

#define ANALOG_AGPIOCTRL(gpio)  ( REG32( ANALOG_BASE + 0x102UL + GPIO_GetGroup(gpio) * 2 ) ) // AGPIO Control Register

#define ANALOG_DEVICE_CAL_FN    ((void (*)(void))((uintptr_t)0x003fce6c))

#define ANALOG_S_ADC(x)         (x <<  0)
#define ANALOG_S_ADCIN_NUM(x)   (x <<  3)
#define ANALOG_S_CMPSS(x)       (x <<  8)
#define ANALOG_S_CMPSS_PMUX(x)  (x << 12)
#define ANALOG_S_CMPSS_NMUX(x)  (x << 16)

enum AnalogPin
{
    AnalogPin_A0  = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM( 0) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(2UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_A1  = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM( 1) | ANALOG_S_CMPSS(CMPSS_1) | ANALOG_S_CMPSS_PMUX(4UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_A2  = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM( 2) | ANALOG_S_CMPSS(CMPSS_1) | ANALOG_S_CMPSS_PMUX(0UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_A3  = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM( 3) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(5UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_A4  = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM( 4) | ANALOG_S_CMPSS(CMPSS_2) | ANALOG_S_CMPSS_PMUX(0UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_A5  = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM( 5) | ANALOG_S_CMPSS(CMPSS_2) | ANALOG_S_CMPSS_PMUX(5UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_A6  = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM( 6) | ANALOG_S_CMPSS(CMPSS_1) | ANALOG_S_CMPSS_PMUX(2UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_A7  = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM( 7) | ANALOG_S_CMPSS(CMPSS_4) | ANALOG_S_CMPSS_PMUX(1UL) | ANALOG_S_CMPSS_NMUX( 1UL),
    AnalogPin_A8  = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM( 8) | ANALOG_S_CMPSS(CMPSS_4) | ANALOG_S_CMPSS_PMUX(4UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_A9  = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM( 9) | ANALOG_S_CMPSS(CMPSS_2) | ANALOG_S_CMPSS_PMUX(2UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_A10 = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM(10) | ANALOG_S_CMPSS(CMPSS_2) | ANALOG_S_CMPSS_PMUX(3UL) | ANALOG_S_CMPSS_NMUX( 0UL),
    AnalogPin_A11 = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM(11) | ANALOG_S_CMPSS(CMPSS_1) | ANALOG_S_CMPSS_PMUX(1UL) | ANALOG_S_CMPSS_NMUX( 1UL),
    AnalogPin_A12 = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM(12) | ANALOG_S_CMPSS(CMPSS_2) | ANALOG_S_CMPSS_PMUX(1UL) | ANALOG_S_CMPSS_NMUX( 1UL),
    AnalogPin_A14 = ANALOG_S_ADC(ADC_A) | ANALOG_S_ADCIN_NUM(14) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(4UL) | ANALOG_S_CMPSS_NMUX(15UL),

    AnalogPin_B0  = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM( 0) | ANALOG_S_CMPSS(CMPSS_2) | ANALOG_S_CMPSS_PMUX(4UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_B1  = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM( 1) | ANALOG_S_CMPSS(CMPSS_2) | ANALOG_S_CMPSS_PMUX(3UL) | ANALOG_S_CMPSS_NMUX( 0UL),
    AnalogPin_B2  = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM( 2) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(0UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_B3  = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM( 3) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(3UL) | ANALOG_S_CMPSS_NMUX( 0UL),
    AnalogPin_B4  = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM( 4) | ANALOG_S_CMPSS(CMPSS_4) | ANALOG_S_CMPSS_PMUX(0UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_B5  = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM( 5) | ANALOG_S_CMPSS(CMPSS_1) | ANALOG_S_CMPSS_PMUX(5UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_B6  = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM( 6) | ANALOG_S_CMPSS(CMPSS_1) | ANALOG_S_CMPSS_PMUX(0UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_B7  = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM( 7) | ANALOG_S_CMPSS(CMPSS_1) | ANALOG_S_CMPSS_PMUX(4UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_B8  = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM( 8) | ANALOG_S_CMPSS(CMPSS_2) | ANALOG_S_CMPSS_PMUX(0UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_B9  = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM( 9) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(5UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_B10 = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM(10) | ANALOG_S_CMPSS(CMPSS_1) | ANALOG_S_CMPSS_PMUX(1UL) | ANALOG_S_CMPSS_NMUX( 1UL),
    AnalogPin_B11 = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM(11) | ANALOG_S_CMPSS(CMPSS_4) | ANALOG_S_CMPSS_PMUX(5UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_B12 = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM(12) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(1UL) | ANALOG_S_CMPSS_NMUX( 1UL),
    AnalogPin_B14 = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM(14) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(4UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_B15 = ANALOG_S_ADC(ADC_B) | ANALOG_S_ADCIN_NUM(15) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(2UL) | ANALOG_S_CMPSS_NMUX(15UL),

    AnalogPin_C0  = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM( 0) | ANALOG_S_CMPSS(CMPSS_1) | ANALOG_S_CMPSS_PMUX(1UL) | ANALOG_S_CMPSS_NMUX( 1UL),
    AnalogPin_C1  = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM( 1) | ANALOG_S_CMPSS(CMPSS_4) | ANALOG_S_CMPSS_PMUX(2UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_C2  = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM( 2) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(1UL) | ANALOG_S_CMPSS_NMUX( 1UL),
    AnalogPin_C3  = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM( 3) | ANALOG_S_CMPSS(CMPSS_4) | ANALOG_S_CMPSS_PMUX(1UL) | ANALOG_S_CMPSS_NMUX( 1UL),
    AnalogPin_C4  = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM( 4) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(4UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_C5  = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM( 5) | ANALOG_S_CMPSS(CMPSS_2) | ANALOG_S_CMPSS_PMUX(1UL) | ANALOG_S_CMPSS_NMUX( 1UL),
    AnalogPin_C6  = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM( 6) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(0UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_C7  = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM( 7) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(5UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_C8  = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM( 8) | ANALOG_S_CMPSS(CMPSS_4) | ANALOG_S_CMPSS_PMUX(0UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_C9  = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM( 9) | ANALOG_S_CMPSS(CMPSS_1) | ANALOG_S_CMPSS_PMUX(0UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_C10 = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM(10) | ANALOG_S_CMPSS(CMPSS_2) | ANALOG_S_CMPSS_PMUX(3UL) | ANALOG_S_CMPSS_NMUX( 0UL),
    AnalogPin_C11 = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM(11) | ANALOG_S_CMPSS(CMPSS_2) | ANALOG_S_CMPSS_PMUX(4UL) | ANALOG_S_CMPSS_NMUX(15UL),
    AnalogPin_C14 = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM(14) | ANALOG_S_CMPSS(CMPSS_4) | ANALOG_S_CMPSS_PMUX(3UL) | ANALOG_S_CMPSS_NMUX( 0UL),
    AnalogPin_C15 = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM(15) | ANALOG_S_CMPSS(CMPSS_3) | ANALOG_S_CMPSS_PMUX(2UL) | ANALOG_S_CMPSS_NMUX(15UL),

    AnalogPin_C12_Tsense = ANALOG_S_ADC(ADC_C) | ANALOG_S_ADCIN_NUM(12) | ANALOG_S_CMPSS(15) | ANALOG_S_CMPSS_PMUX(15UL) | ANALOG_S_CMPSS_NMUX(15UL)
};


#endif /* ANALOG_H_ */
